### PR TITLE
fix minor spelling mistakes

### PR DESCRIPTION
**Pull request by realsobek**

### CODE REVIEW

**Comment by sergiomb2** [comment]
I will accept and merge this PR except for VirtualBox-4.3.0-libcxx.patch .
you are fixing things from source code in the patch.

**Comment by realsobek** [comment]
Thank you :)
I am going to submit a patch upstream because the problem is still there (it even has been duplicated see line 116 and 173): https://www.virtualbox.org/browser/vbox/trunk/src/VBox/Storage/testcase/Makefile.kmk

Do you still want to exclude the file (because it is specific to version 4.3.0)?
If so, can you skip the file during merge or shall I drop it from the pull request?

**Comment by sergiomb2** [comment]
if you drop it from pull request , and squash into the commit I will appreciate .
Thanks

not_in_use directory means that the patches are not in use , but I keep it to review one day ...

**Comment by realsobek** [comment]
The file has been dropped and the PR updated.

**Comment by sergiomb2** [comment]
merged, for some problem "remote: Sync with github disabled" , so you cant see it

**Comment by sergiomb2** [comment]
you can check here https://pkgs.rpmfusion.org/cgit/free/VirtualBox.git/

**Comment by realsobek** [comment]
Thank you :)

I sent the patch upstream: https://www.virtualbox.org/pipermail/vbox-dev/2018-March/014972.html
From my point of view nothing left to do. Hence I click on [Close and comment].

**Pull request closed without merging**
